### ISSUE TITLE
Difficulty Accessing Repository Submodules (DataSynthesizer)

### ISSUE THREAD

**Issue by gnamiro** [David-Pujol/Prefair#1]
Hello,

I've been trying to conduct some experiments using your repository, but I'm facing issues accessing the content of the "DataSynthesize"directory. Initially, I focused on the main repositories mentioned in the Readme, but even after cloning and replacing the files, I couldn't run the experiments in the notebooks. Could you provide some guidance on this?

Thanks.

**Comment by steaven20** [comment]
Hello Mr. David,
Thanks for sharing your code interesting.
Also, thank Mr. Gnamiro for sharing your problem faced.
I have met the same problem.
The project misses the function  ‘discribe_dataset_in_fair_correclated_attribut_mode’.
I am looking forward to your response.
Wish you have a nice day.
Sincerely.
![pro](https://github.com/David-Pujol/Prefair/assets/35631807/9a5bc32c-8ced-47a4-9a90-d5eb329e935a)

**Comment by David-Pujol** [comment]
I added DataDescriber.py file that was previously missing. Replacing DataSynthesizer's DataDescriber file with that one should fix the issue.
