### ISSUE TITLE
A request for function "fair_greedy_bayes"

### ISSUE THREAD

**Issue by steaven20** [David-Pujol/Prefair#2]
Hello Mr. David,

Thanks a lot for your last help.
Sorry for bother you again, just like a Whack-a-mole. I have met another problem.
After adding the new file DataDescriber.py, the program can‘t find the function "fair_greedy_bayes" in the file PrivBayes.py.
I can't also find this function in the file FairPrivBayes.py.
I was wondering if you could add the function "fair_greedy_bayes" to the project.
I am looking forward to your response.
Wish you have a nice day.
Sincerely.

![屏幕截图 2024-03-04 203941](https://github.com/David-Pujol/Prefair/assets/35631807/ef0fbc48-a110-401e-8b1e-8b86bd0249da)
![屏幕截图 2024-03-04 204036](https://github.com/David-Pujol/Prefair/assets/35631807/60939f78-c4a0-4fe6-a358-6a906d3b6eb4)

**Comment by David-Pujol** [comment]
I changed the FairPrivBayes file to now be a replacement for DataSynthesizers priv bayes file. That should fix the issue. Let me know if there are any other issues.
